version: "2"
services:
  node:
    #image: "node:8"
    build: .
    user: "node"
    #working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
        #expose:
        #- "8080"
    ports:
     - 8080:8080
    command: "npm start"
